#!/usr/bin/env python3
"""Small PyTorch prompt/reply transformer for comparison with Vanus Java.

This file intentionally keeps the entire learning program in one place so it
can be read from top to bottom:

1. Read ``prompt<TAB>response`` rows from a TSV file.
2. Convert text to UTF-8 byte token IDs.
3. Build a small causal transformer.
4. Train it to predict response bytes one token at a time.
5. Save the learned numbers in a checkpoint.
6. Load that checkpoint and generate replies in the terminal.

PyTorch performs tensor math and automatic differentiation for us. There is no
hidden pretrained model and no call to an online AI service. ``TinyTransformer``
starts with random weights and learns only from the TSV supplied to ``train``.

Useful vocabulary while reading this file:

* token: one integer representing a UTF-8 byte or a structural marker;
* tensor: a rectangular collection of numbers, similar to a multidimensional
  array;
* parameter/weight: a trainable number changed by the optimizer;
* logit: an unnormalized score for a possible next token;
* gradient: the calculated direction in which a weight should move to reduce
  the prediction error;
* checkpoint: a file containing the model's learned weights and configuration.
"""

from __future__ import annotations

import argparse
import math
import random
import time
from dataclasses import asdict, dataclass
from pathlib import Path

# PyTorch supplies tensors, neural-network building blocks, automatic
# differentiation, optimizers, and checkpoint serialization.
import torch
from torch import nn
from torch.nn import functional as F


# ---------------------------------------------------------------------------
# Token vocabulary
# ---------------------------------------------------------------------------

# Every possible byte occupies IDs 0 through 255. UTF-8 can represent any text
# as bytes, so this model does not need a word list or an "unknown word" token.
BYTE_VALUES = 256

# These four IDs live immediately above the byte range. They describe the
# structure of a conversation and can never be confused with real text bytes.
#
# BOS       = beginning of the complete sequence
# EOS       = the assistant has finished its response
# USER      = user text starts after this marker
# ASSISTANT = assistant text should start after this marker
BOS, EOS, USER, ASSISTANT = 256, 257, 258, 259
VOCABULARY = 260

# PyTorch cross_entropy ignores any target equal to ignore_index. We replace
# targets in the prompt portion with this value because the model should learn
# the response, not spend capacity learning to reproduce the user's prompt.
IGNORE = -100


@dataclass(frozen=True)
class ModelConfig:
    """The dimensions that determine the transformer's shape and capacity.

    ``width`` is the size of every token vector. ``hidden`` is the larger
    intermediate size in each feed-forward block. ``layers`` is the number of
    repeated transformer blocks. ``heads`` is the number of parallel attention
    views in each block. ``context`` is the maximum number of token positions
    the model can process at once.

    The dataclass is frozen so the architecture cannot accidentally change
    after model construction. A checkpoint records these values and recreates
    the same architecture before loading its weights.
    """

    width: int
    hidden: int
    layers: int
    heads: int
    context: int
    vocabulary: int = VOCABULARY


# These presets roughly mirror the Java experiment's named sizes. PyTorch's
# standard layer includes different biases, normalization, and position
# embeddings, so the exact parameter counts are not identical to Java.
PRESETS = {
    "tiny": ModelConfig(32, 64, 1, 4, 128),
    "200k": ModelConfig(96, 176, 2, 4, 128),
    "1m": ModelConfig(160, 320, 4, 8, 256),
}


def encode(text: str) -> list[int]:
    """Convert Unicode text to raw UTF-8 byte IDs.

    For ASCII, one character is one token: ``hello`` becomes
    ``[104, 101, 108, 108, 111]``. Characters such as curly quotes and emoji
    use multiple UTF-8 bytes and therefore multiple tokens.
    """

    return list(text.encode("utf-8"))


def decode(tokens: list[int]) -> str:
    """Convert generated byte IDs back to displayable text.

    Structural IDs 256 through 259 are excluded because they are instructions
    to the model rather than text. ``errors="replace"`` keeps the console alive
    if an undertrained model emits an incomplete multi-byte UTF-8 character.
    """

    return bytes(token for token in tokens if 0 <= token < BYTE_VALUES).decode(
        "utf-8", errors="replace"
    )


def prompt_tokens(prompt: str) -> list[int]:
    """Wrap user text in the same conversation structure used for training.

    ``hello`` becomes ``[BOS, USER, h, e, l, l, o, ASSISTANT]`` where the
    letters stand for their numeric byte values. Ending on ASSISTANT tells the
    model that the next token should be the first byte of its response.
    """

    return [BOS, USER, *encode(prompt), ASSISTANT]


def load_pairs(path: Path) -> list[tuple[str, str]]:
    """Read and strictly validate ``prompt<TAB>response`` training rows.

    Empty lines are harmless and skipped. Every other line must have exactly
    two nonempty fields. Failing early is valuable: otherwise a missing tab
    could quietly train the model on the wrong lesson for thousands of steps.
    """

    pairs: list[tuple[str, str]] = []
    with path.open(encoding="utf-8") as source:
        for line_number, raw_line in enumerate(source, 1):
            line = raw_line.rstrip("\r\n")
            if not line:
                continue
            fields = line.split("\t")
            if len(fields) != 2 or not all(fields):
                raise ValueError(
                    f"{path}:{line_number}: expected prompt<TAB>response"
                )
            pairs.append((fields[0], fields[1]))
    if not pairs:
        raise ValueError(f"Dataset is empty: {path}")
    return pairs


class TinyTransformer(nn.Module):
    """A decoder-style language model assembled from standard PyTorch layers.

    PyTorch calls the repeated building block ``TransformerEncoderLayer``, but
    the causal mask in ``forward`` makes it behave as a decoder-only language
    model: a position may read itself and earlier positions, never the future.

    Data flows through the model like this:

    token IDs
      -> token embeddings + position embeddings
      -> causal self-attention and feed-forward blocks
      -> final normalization
      -> one score for every possible next token

    Tensor-shape notation used below:

    * B = number of examples in the batch;
    * T = number of token positions in each padded example;
    * W = model width;
    * V = vocabulary size, which is 260 here.
    """

    def __init__(self, config: ModelConfig):
        super().__init__()
        self.config = config

        # Embedding is a learned lookup table with shape [V, W]. Looking up a
        # [B, T] token tensor produces [B, T, W] vectors. IDs are merely labels;
        # these vectors are the representations the transformer actually uses.
        self.token_embedding = nn.Embedding(config.vocabulary, config.width)

        # Attention does not inherently know token order. This learned table has
        # one W-dimensional vector for every position from 0 to context - 1.
        self.position_embedding = nn.Embedding(config.context, config.width)

        # One transformer block contains:
        #   1. multi-head self-attention, which mixes earlier context;
        #   2. a feed-forward network, which transforms each position;
        #   3. residual connections and LayerNorm for stable training.
        # dropout=0 keeps this small educational experiment deterministic.
        # norm_first=True means LayerNorm happens before attention/feed-forward.
        layer = nn.TransformerEncoderLayer(
            d_model=config.width,
            nhead=config.heads,
            dim_feedforward=config.hidden,
            dropout=0.0,
            activation="gelu",
            batch_first=True,
            norm_first=True,
        )
        self.transformer = nn.TransformerEncoder(
            layer, config.layers, enable_nested_tensor=False
        )

        # Normalize once more after the final repeated transformer block.
        self.final_norm = nn.LayerNorm(config.width)

        # Convert each W-dimensional hidden vector into V next-token scores.
        # There is no bias because this matrix shares weights with the input
        # embedding table on the following line.
        self.output = nn.Linear(config.width, config.vocabulary, bias=False)

        # Weight tying means the [V, W] table used to read tokens is also used to
        # score tokens for output. This saves parameters and gives a small model
        # one consistent learned representation per token.
        self.output.weight = self.token_embedding.weight

        # PyTorch embeddings default to standard deviation 1.0. That is far too
        # large when the same matrix is also the output projection: initial
        # logits become extreme and loss can start around 90 instead of ln(260),
        # roughly 5.56. Small initial values give training a stable beginning.
        nn.init.normal_(self.token_embedding.weight, mean=0.0, std=0.02)
        nn.init.normal_(self.position_embedding.weight, mean=0.0, std=0.02)

    def forward(
        self, tokens: torch.Tensor, padding_mask: torch.Tensor | None = None
    ) -> torch.Tensor:
        """Calculate next-token logits for every input position.

        ``tokens`` has integer shape [B, T]. ``padding_mask``, when supplied,
        has boolean shape [B, T], with True at artificial padding positions.
        The returned floating-point tensor has shape [B, T, V].

        This method calculates predictions only. PyTorch records the operations
        during training so ``loss.backward()`` can later compute gradients.
        """

        # All examples in a padded batch share T, so dimension 1 is sequence
        # length. There are no position vectors beyond the context limit.
        length = tokens.size(1)
        if length > self.config.context:
            raise ValueError(f"Sequence exceeds context length {self.config.context}")
        # arange creates [0, 1, ..., T-1]. Broadcasting lets one [T, W]
        # position table be added to token embeddings for every batch row.
        positions = torch.arange(length, device=tokens.device)
        hidden = self.token_embedding(tokens) + self.position_embedding(positions)

        # This upper-triangular matrix blocks attention to future columns.
        # At row i, columns greater than i are True (hidden). Without it, the
        # model could see correct future response tokens and cheat in training.
        causal_mask = torch.triu(
            torch.ones(length, length, dtype=torch.bool, device=tokens.device),
            diagonal=1,
        )
        # The causal mask controls time direction. The padding mask separately
        # prevents short examples from attending to filler positions that were
        # added only to make the batch rectangular.
        hidden = self.transformer(
            hidden, mask=causal_mask, src_key_padding_mask=padding_mask
        )

        # [B, T, W] -> [B, T, V]. These values are logits rather than
        # probabilities; cross_entropy applies the required log-softmax in a
        # numerically stable way.
        return self.output(self.final_norm(hidden))


def training_example(
    prompt: str, response: str, context: int
) -> tuple[list[int], list[int]]:
    """Build one shifted next-token lesson and mask its prompt targets.

    For a conceptual sequence ``[BOS, USER, prompt, ASSISTANT, reply, EOS]``,
    inputs omit the last token and targets omit the first token. Target position
    i is therefore the correct token after input position i.

    Prompt target positions become IGNORE. The model still reads the prompt as
    context, but only response bytes and EOS affect the supervised loss.
    """

    prefix = prompt_tokens(prompt)
    sequence = [*prefix, *encode(response), EOS]

    # The forward pass receives sequence[:-1], so its length—not the full
    # sequence including final EOS—must fit within the context.
    if len(sequence) - 1 > context:
        raise ValueError(
            f"Example is {len(sequence) - 1} tokens but context is {context}: {prompt!r}"
        )
    inputs = sequence[:-1]
    targets = sequence[1:]

    # The target aligned with ASSISTANT is the first response byte and must not
    # be ignored. That is why masking stops at len(prefix) - 1.
    targets[: len(prefix) - 1] = [IGNORE] * (len(prefix) - 1)
    return inputs, targets


def corrupt_prompt(prompt: str, rng: random.Random) -> str:
    """Return one small prompt variation for robustness training.

    The operation deliberately changes only the prompt; its desired response
    stays the same. This gives the model evidence that nearby forms such as
    ``hello!`` and ``hello`` or ``doing`` and ``doin`` may deserve the same
    answer. One candidate is selected so corruption remains light rather than
    destroying the sentence.
    """

    choices: list[str] = []

    # Candidate 1: remove final sentence punctuation.
    without_ending = prompt.rstrip(".!?")
    if without_ending and without_ending != prompt:
        choices.append(without_ending)
    # Candidate 2: remove the first comma.
    if "," in prompt:
        choices.append(prompt.replace(",", "", 1))
    # Candidate 3: delete a letter that has letters on both sides. Restricting
    # deletion to the inside of a word gives examples resembling common typos.
    internal = [
        index
        for index in range(1, len(prompt) - 1)
        if prompt[index - 1 : index + 2].isalpha()
    ]
    if internal:
        index = rng.choice(internal)
        choices.append(prompt[:index] + prompt[index + 1 :])
    # Candidate 4: transpose two neighboring letters, such as "the" -> "hte".
    adjacent = [
        index
        for index in range(len(prompt) - 1)
        if prompt[index].isalpha() and prompt[index + 1].isalpha()
    ]
    if adjacent:
        index = rng.choice(adjacent)
        choices.append(
            prompt[:index]
            + prompt[index + 1]
            + prompt[index]
            + prompt[index + 2 :]
        )
    # dict preserves order while removing duplicates. If a very short prompt
    # offers no useful corruption, returning it unchanged is safer than empty
    # or nonsensical training input.
    choices = list(dict.fromkeys(value for value in choices if value and value != prompt))
    return rng.choice(choices) if choices else prompt


def make_batch(
    pairs: list[tuple[str, str]],
    config: ModelConfig,
    batch_size: int,
    prompt_noise: float,
    rng: random.Random,
    device: torch.device,
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    """Randomly sample TSV rows and pack them into padded PyTorch tensors.

    The returned tensors are:

    * inputs: integer token IDs with shape [B, T];
    * targets: desired next IDs with shape [B, T], using IGNORE where no loss
      should be calculated;
    * padding: booleans with shape [B, T], True only at filler positions.

    T is the longest selected example in this batch, not the full configured
    context. Using only the needed length avoids unnecessary attention work.
    """

    examples = []
    for _ in range(batch_size):
        # Random sampling means a "step" is not a complete pass through the TSV.
        prompt, response = rng.choice(pairs)

        # prompt_noise=0.15 means roughly 15% of sampled prompts are modified.
        if rng.random() < prompt_noise:
            prompt = corrupt_prompt(prompt, rng)
        examples.append(training_example(prompt, response, config.context))
    # Begin with rectangular tensors filled entirely as padding. EOS is a legal
    # harmless filler input, while IGNORE ensures filler targets add no loss.
    length = max(len(inputs) for inputs, _ in examples)
    inputs = torch.full((batch_size, length), EOS, dtype=torch.long)
    targets = torch.full((batch_size, length), IGNORE, dtype=torch.long)
    padding = torch.ones((batch_size, length), dtype=torch.bool)
    for row, (example_inputs, example_targets) in enumerate(examples):
        size = len(example_inputs)

        # Copy the real variable-length example into the left side of its row.
        inputs[row, :size] = torch.tensor(example_inputs)
        targets[row, :size] = torch.tensor(example_targets)

        # False means "real token, attention may use it." Remaining positions
        # stay True and are hidden from attention.
        padding[row, :size] = False

    # Model parameters and input tensors must live on the same device.
    return inputs.to(device), targets.to(device), padding.to(device)


def choose_device(requested: str) -> torch.device:
    """Select an accelerator when available, otherwise use the CPU.

    CUDA is NVIDIA's GPU backend. MPS is Apple's Metal backend. Explicit
    ``--device cpu`` bypasses automatic selection and is useful for comparison
    or troubleshooting.
    """

    if requested != "auto":
        return torch.device(requested)
    if torch.cuda.is_available():
        return torch.device("cuda")
    if torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


def learning_rate(step: int, steps: int) -> float:
    """Return a warmup-plus-cosine learning rate for one training step.

    Warmup grows from a small rate to the base rate over ten steps, avoiding a
    violent first update on random weights. The cosine factor then decays from
    near 1.0 toward 0.1, making later updates gentler without reaching zero.
    """

    warmup = min(1.0, step / 10.0)
    cosine = 0.1 + 0.9 * 0.5 * (1.0 + math.cos(math.pi * step / steps))
    return 0.003 * warmup * cosine


def train(args: argparse.Namespace) -> None:
    """Train from random weights and save a new PyTorch checkpoint.

    Each loop iteration samples a batch, runs the model, measures response-token
    error, backpropagates that error, and updates all trainable parameters once.
    This command intentionally starts fresh; loading and continuing optimizer
    state could be added later as a separate educational step.
    """

    # Validate cheap command-line mistakes before allocating a model.
    if args.steps <= 0 or args.batch_size <= 0:
        raise ValueError("Steps and batch size must be positive")
    if not 0.0 <= args.prompt_noise <= 1.0:
        raise ValueError("Prompt noise must be between 0 and 1")
    # Fixed seeds make repeated CPU experiments easier to compare. Exact results
    # can still differ across PyTorch versions, devices, and hardware kernels.
    random.seed(args.seed)
    torch.manual_seed(args.seed)
    rng = random.Random(args.seed)
    device = choose_device(args.device)
    config = PRESETS[args.size]
    pairs = load_pairs(args.data)

    # Validate every row before spending time training.
    for prompt, response in pairs:
        training_example(prompt, response, config.context)
    # All weights begin random. Calling .to(device) moves parameter tensors to
    # the CPU/GPU selected above.
    model = TinyTransformer(config).to(device)

    # AdamW remembers moving averages for every parameter. weight_decay gently
    # discourages very large weights; lr is replaced by our schedule each step.
    optimizer = torch.optim.AdamW(model.parameters(), lr=0.003, weight_decay=0.01)

    # numel() counts scalar trainable numbers, not bytes or phrases.
    parameter_count = sum(parameter.numel() for parameter in model.parameters())
    print(
        f"Training {parameter_count:,} parameters on {len(pairs)} rows "
        f"device={device} steps={args.steps} batch={args.batch_size}"
    )
    started = time.monotonic()
    last_report = started
    loss_total = 0.0
    loss_steps = 0
    # train() enables training behavior in modules. Dropout is zero here, but
    # setting the mode correctly keeps the lifecycle conventional and clear.
    model.train()
    for step in range(1, args.steps + 1):
        # inputs/targets are [B, T]; padding tells attention which positions are
        # artificial. A different random batch is selected on every step.
        inputs, targets, padding = make_batch(
            pairs, config, args.batch_size, args.prompt_noise, rng, device
        )
        # PyTorch optimizers allow each parameter group to have its own rate.
        # This model has one group, updated from the schedule before the step.
        rate = learning_rate(step, args.steps)
        for group in optimizer.param_groups:
            group["lr"] = rate
        # Gradients accumulate by default in PyTorch. Clear the previous step's
        # gradients before calculating new ones. set_to_none can save work.
        optimizer.zero_grad(set_to_none=True)

        # logits shape: [B, T, V]. The model predicts every next-token position
        # in parallel during training even though chat generates sequentially.
        logits = model(inputs, padding)

        # cross_entropy expects a collection of [item, class] scores and one
        # class ID per item. Flatten B and T while retaining V classes. IGNORE
        # removes prompt and padded positions from the average.
        loss = F.cross_entropy(
            logits.reshape(-1, config.vocabulary), targets.reshape(-1), ignore_index=IGNORE
        )
        # Autograd follows the recorded forward operations backward and stores a
        # gradient beside every trainable parameter.
        loss.backward()

        # clip_grad_norm_ returns the norm before clipping. If it exceeds 1.0,
        # gradients are scaled down together to prevent an unstable update.
        gradient_norm = nn.utils.clip_grad_norm_(model.parameters(), 1.0)

        # This is the moment learned weights actually change.
        optimizer.step()
        loss_total += loss.item()
        loss_steps += 1
        now = time.monotonic()
        # Time-based reporting avoids thousands of console lines on fast runs.
        # The final step is always printed even when four seconds have not passed.
        if now - last_report >= 4.0 or step == args.steps:
            elapsed = now - started
            rate_steps = step / elapsed if elapsed else 0.0
            remaining = (args.steps - step) / rate_steps if rate_steps else 0.0
            print(
                f"step={step}/{args.steps} loss={loss_total / loss_steps:.4f} "
                f"gradNorm={float(gradient_norm):.4f} lr={rate:.7f} "
                f"elapsed={format_time(elapsed)} eta={format_time(remaining)}"
            )
            loss_total = 0.0
            loss_steps = 0
            last_report = now
    # Create only the checkpoint's parent directory. The TSV and source files
    # are never copied into it.
    args.checkpoint.parent.mkdir(parents=True, exist_ok=True)

    # A state_dict maps stable parameter names to tensors. Saving config first
    # allows load_model() to rebuild matching layers before assigning weights.
    # Optimizer state is retained for possible future continuation support.
    torch.save(
        {
            "format": 1,
            "config": asdict(config),
            "model": model.state_dict(),
            "optimizer": optimizer.state_dict(),
            "steps": args.steps,
        },
        args.checkpoint,
    )
    print(f"Saved checkpoint: {args.checkpoint}")


def load_model(path: Path, device: torch.device) -> TinyTransformer:
    """Rebuild a model from a checkpoint and prepare it for generation.

    A state dictionary contains tensors but is not itself a usable model. We
    first recreate ``TinyTransformer`` from the saved dimensions, then copy each
    saved tensor into the corresponding named parameter.

    ``weights_only=False`` is needed because this checkpoint also contains plain
    Python metadata and optimizer state. Only load checkpoints you trust, since
    PyTorch checkpoint loading uses Python pickle semantics.
    """

    checkpoint = torch.load(path, map_location=device, weights_only=False)

    # An explicit format number gives future code a clean way to reject an
    # incompatible layout rather than failing later with confusing tensor errors.
    if checkpoint.get("format") != 1:
        raise ValueError("Unsupported checkpoint format")
    config = ModelConfig(**checkpoint["config"])
    model = TinyTransformer(config).to(device)
    model.load_state_dict(checkpoint["model"])

    # Evaluation mode disables training-only module behavior. Dropout is zero in
    # this model, but setting eval mode is still the correct inference contract.
    model.eval()
    return model


@torch.inference_mode()
def generate(
    model: TinyTransformer,
    prompt: str,
    max_tokens: int,
    temperature: float,
    device: torch.device,
) -> str:
    """Generate one response by repeatedly choosing the next token.

    Unlike training, generation has no known target and no backward pass.
    ``inference_mode`` disables gradient bookkeeping, reducing memory and work.

    With temperature <= 0, generation is greedy: always choose the largest
    logit. With positive temperature, divide logits by temperature, apply
    softmax, and randomly sample. Higher temperature flattens probabilities and
    creates more variety; it also creates more errors in a tiny model.
    """

    # Begin with exactly the same structural prefix used by training. The last
    # current token is ASSISTANT, so its logits predict the first response byte.
    tokens = prompt_tokens(prompt)
    if len(tokens) >= model.config.context:
        raise ValueError(f"Prompt is too long for context {model.config.context}")
    generated: list[int] = []

    # Generation cannot exceed either the user's max_tokens request or the
    # number of positions remaining in the fixed context window.
    for _ in range(min(max_tokens, model.config.context - len(tokens))):

        # Shape [1, current_length]: generation handles one prompt at a time.
        inputs = torch.tensor([tokens], dtype=torch.long, device=device)

        # Forward returns [1, T, V]. Select batch row 0 and position -1 because
        # only the newest position's V scores determine the next token.
        logits = model(inputs)[0, -1]
        if temperature <= 0:
            # argmax returns the ID with the greatest score.
            next_token = int(logits.argmax())
        else:
            # Sampling can select a likely alternative rather than always taking
            # the top choice. A fixed seed makes the random stream reproducible.
            probabilities = F.softmax(logits / temperature, dim=-1)
            next_token = int(torch.multinomial(probabilities, 1))

        # EOS is an instruction, not visible response text.
        if next_token == EOS:
            break

        # Keep response-only bytes for decoding, and append the same token to the
        # full context so the following prediction can see what was just emitted.
        generated.append(next_token)
        tokens.append(next_token)
    return decode(generated)


def chat(args: argparse.Namespace) -> None:
    """Load one checkpoint and run a simple terminal input/output loop.

    Each entered line is a separate prompt. The code does not prepend previous
    turns, update weights, or save new knowledge during chat. `/quit`, `/exit`,
    Ctrl-D, and Ctrl-C leave the loop.
    """

    device = choose_device(args.device)
    model = load_model(args.checkpoint, device)
    print(
        f"Loaded {args.checkpoint} on {device}. Type /quit to stop.\n"
        "This model answers one prompt at a time; it does not retain chat history."
    )
    while True:
        try:
            prompt = input("You: ").strip()
        except (EOFError, KeyboardInterrupt):
            print()
            return
        if prompt.lower() in {"/quit", "/exit"}:
            return
        if not prompt:
            continue

        # generate() may invoke the model many times: once for each emitted byte.
        reply = generate(model, prompt, args.max_tokens, args.temperature, device)
        print(f"VanusPy: {reply}")


def reply(args: argparse.Namespace) -> None:
    """Generate one response for scripting, then exit immediately."""

    device = choose_device(args.device)
    model = load_model(args.checkpoint, device)
    print(generate(model, args.prompt, args.max_tokens, args.temperature, device))


def format_time(seconds: float) -> str:
    """Format a duration as HH:MM:SS for compact training progress logs."""

    total = max(0, int(seconds))
    hours, remainder = divmod(total, 3600)
    minutes, seconds = divmod(remainder, 60)
    return f"{hours:02d}:{minutes:02d}:{seconds:02d}"


def parser() -> argparse.ArgumentParser:
    """Describe the command-line interface and return its argument parser.

    Each subcommand stores its handler in ``args.run``. ``main`` therefore does
    not need a large if/elif chain to decide which operation was requested.
    """

    root = argparse.ArgumentParser(description=__doc__)
    commands = root.add_subparsers(dest="command", required=True)

    # Training-specific settings. Path conversion and basic choice validation
    # happen automatically inside argparse before train() is called.
    train_parser = commands.add_parser("train", help="Train from a prompt/response TSV")
    train_parser.add_argument("--data", type=Path, required=True)
    train_parser.add_argument("--checkpoint", type=Path, required=True)
    train_parser.add_argument("--size", choices=PRESETS, default="1m")
    train_parser.add_argument("--steps", type=int, default=2000)
    train_parser.add_argument("--batch-size", type=int, default=4)
    train_parser.add_argument("--prompt-noise", type=float, default=0.15)
    train_parser.add_argument("--seed", type=int, default=42)
    train_parser.add_argument("--device", default="auto", help="auto, cpu, cuda, or mps")
    train_parser.set_defaults(run=train)

    # chat and reply share checkpoint and generation options. Only reply needs a
    # positional prompt because chat obtains prompts interactively from input().
    for name, help_text, function in (
        ("chat", "Start an interactive console chat", chat),
        ("reply", "Generate one reply and exit", reply),
    ):
        command = commands.add_parser(name, help=help_text)
        command.add_argument("--checkpoint", type=Path, required=True)
        command.add_argument("--device", default="auto")
        command.add_argument("--max-tokens", type=int, default=100)
        command.add_argument("--temperature", type=float, default=0.0)
        if name == "reply":
            command.add_argument("prompt")
        command.set_defaults(run=function)
    return root


def main() -> None:
    """Parse the command line and invoke the selected subcommand."""

    args = parser().parse_args()
    args.run(args)


if __name__ == "__main__":
    # This guard runs main only when executing ``python3 vanus.py ...``. It lets
    # another Python file import functions from this module without starting the
    # command-line program as an accidental side effect.
    main()
